codingjobs/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import frontpage, signup

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('signup/', signup, name='signup'),
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),

    path('dashboard/', include('profiles.urls')),
    path('jobs/', include('jobs.urls')),
    path('notifications/', include('notifications.urls')),
]

jobs/urls.py
from django.urls import path, include

from .views import job_detail, add_job_request, edit_job_request, apply_for_job, search
from .api import api_search

urlpatterns = [
    path('api/busca/', api_search, name='api_search'),
    path('busca/', search, name='search'),
    path('add/', add_job_request, name='add_job_request'),
    path('<int:job_id>/edit/', edit_job_request, name='edit_job_request'),
    path('<int:job_id>/', job_detail, name='job_detail'),
    path('<int:job_id>/apply/', apply_for_job, name='apply_for_job'),
]

jobs/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Job(models.Model):
    TAMANHO_1_9 = 'tamanho_1-9'
    TAMANHO_10_49 = 'tamanho_10-49'
    TAMANHO_50_99 = 'tamanho_50-99'
    TAMANHO_100 = 'tamanho_100'

    CHOICES_TAMANHO = (
        (TAMANHO_1_9, '1-9'),
        (TAMANHO_10_49, '10-49'),
        (TAMANHO_50_99, '50-99'),
        (TAMANHO_100, '100+')
    )

    ATIVO = 'ativo'
    OCUPADO = 'ocupado'
    ARQUIVADO = 'arquivado'

    CHOICES_STATUS = (
        (ATIVO, 'Ativo'),
        (OCUPADO, 'Ocupado'),
        (ARQUIVADO, 'Arquivado')
    )

    titulo = models.CharField(max_length=255)
    descricao_curta = models.TextField()
    descricao_longa = models.TextField(blank=True, null=True)
    nome_companhia = models.CharField(max_length=255, default='')
    endereco_companhia = models.CharField(max_length=255, null=True, blank=True)
    cep_companhia = models.CharField(max_length=255, null=True, blank=True)
    cidade_companhia = models.CharField(max_length=255, null=True, blank=True)
    pais_companhia = models.CharField(max_length=255, null=True, blank=True)
    tamanho_companhia = models.CharField(max_length=20, choices=CHOICES_TAMANHO, default=TAMANHO_1_9)
    criado_por = models.ForeignKey(User, related_name='jobs', on_delete=models.CASCADE)
    criado_em = models.DateTimeField(auto_now_add=True)
    modificado_em = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=ATIVO)

    def __str__(self):
        return self.titulo

class Application(models.Model):
    trabalho = models.ForeignKey(Job, related_name='applications', on_delete=models.CASCADE)
    conteudo = models.TextField()
    experiencia = models.TextField()
    criado_por = models.ForeignKey(User, related_name='applications', on_delete=models.CASCADE)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.conteudo

jobs/forms.py
from django import forms
from .models import Job, Application

class addJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['titulo', 'descricao_curta', 'descricao_longa', 'nome_companhia', 'endereco_companhia', 'cep_companhia', 'cidade_companhia', 'pais_companhia', 'tamanho_companhia']

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['conteudo', 'experiencia']

jobs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from notifications.utilities import create_notification
from .models import Job
from .forms import addJobForm, ApplicationForm

# Create your views here.
def search(request):
    return render(request, 'jobs/search.html')

def job_detail(request, job_id):
    job = Job.objects.get(pk=job_id)

    return render(request, 'jobs/job_detail.html', { 'job': job })

@login_required
def apply_for_job(request, job_id):
    job = Job.objects.get(pk=job_id)
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            application = form.save(commit=False)
            application.trabalho = job
            application.criado_por = request.user
            application.save()

            create_notification(request, job.criado_por, 'application', application.id)

            return redirect('dashboard')
    else:
        form = ApplicationForm()

    return render(request, 'jobs/apply_for_job.html', {'form': form, 'job': job})

@login_required
def add_job_request(request):
    if request.method == 'POST':
        form = addJobForm(request.POST)
        if form.is_valid():
            job = form.save(commit=False)
            job.criado_por = request.user
            job.save()

            return redirect('dashboard')

    else:
        form = addJobForm()

    return render(request, 'jobs/add_job.html', {'form': form})

@login_required
def edit_job_request(request, job_id):
    job = get_object_or_404(Job, pk=job_id, criado_por=request.user)

    if request.method == 'POST':
        form = addJobForm(request.POST, instance=job)
        if form.is_valid():
            job = form.save(commit=False)
            job.status = request.POST.get('status')
            job.save()

            return redirect('dashboard')

    else:
        form = addJobForm(instance=job)

    return render(request, 'jobs/edit_job.html', {'form': form, 'job': job})

jobs/templates/jobs/add_job.html
{% extends 'core/base.html' %} {% block content %}
<div id="add-job-app">
  <h1 class="title">Adicionar Trabalho</h1>
  <form action="." method="post" v-on:submit="validateForm()">
    {% csrf_token %} {% if form.errors %} {% for error in form.errors %}
    <div class="notification is-danger"><p>{{ error }}</p></div>
    {% endfor %} {% endif %}
    <div class="notification is-danger" v-if="errors.length">
      <p v-for="error in errors">[[ error ]]</p>
    </div>
    <fieldset class="box">
      <legend class="subtitle is-6">Informações Básicas</legend>
      <div class="field">
        <label class="label" for="id_titulo">Título</label>
        <div class="control">
          <input
            class="input"
            type="text"
            name="titulo"
            id="id_titulo"
            v-model="titulo"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_descricao_curta">Descrição Curta</label>
        <div class="control">
          <textarea
            class="textarea"
            name="descricao_curta"
            id="id_descricao_curta"
            v-model="descricao_curta"
          ></textarea>
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_descricao_longa">Descrição Longa</label>
        <div class="control">
          <textarea
            class="textarea"
            name="descricao_longa"
            id="id_descricao_longa"
          ></textarea>
        </div>
      </div>
    </fieldset>
    <fieldset class="box">
      <legend class="subtitle is-6">Informações da Companhia</legend>
      <div class="field">
        <label class="label" for="id_nome_companhia">Nome da Companhia</label>
        <div class="control">
          <input
            type="text"
            name="nome_companhia"
            id="id_nome_companhia"
            class="input"
            v-model="nome_companhia"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_endereco_companhia"
          >Endereço da Companhia</label
        >
        <div class="control">
          <input
            type="text"
            name="endereco_companhia"
            id="id_endereco_companhia"
            class="input"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_cep_companhia">CEP da Companhia</label>
        <div class="control">
          <input
            type="text"
            name="cep_companhia"
            id="id_cep_companhia"
            class="input"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_cidade_companhia"
          >Cidade da Companhia</label
        >
        <div class="control">
          <input
            type="text"
            name="cidade_companhia"
            id="id_cidade_companhia"
            class="input"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_pais_companhia">País da Companhia</label>
        <div class="control">
          <input
            type="text"
            name="pais_companhia"
            id="id_pais_companhia"
            class="input"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_tamanho_companhia"
          >Tamanho da Companhia</label
        >
        <div class="control">
          <div class="select">
            <select
              name="tamanho_companhia"
              id="id_tamanho_companhia"
              v-model="tamanho_companhia"
            >
              <option value="tamanho_1-9" selected>1-9</option>
              <option value="tamanho_10-49">10-49</option>
              <option value="tamanho_50-99">50-99</option>
              <option value="tamanho_100">100+</option>
            </select>
          </div>
        </div>
      </div>
    </fieldset>
    <div class="field">
      <div class="control">
        <button class="button is-success">Enviar</button>
      </div>
    </div>
  </form>
</div>
{% endblock %} {% block scripts %}
<script>
  const AddJobApp = {
    data() {
      return {
        titulo: "",
        nome_companhia: "",
        descricao_curta: "",
        tamanho_companhia: "",
        errors: [],
      };
    },
    delimiters: ["[[", "]]"],
    methods: {
      validateForm(e) {
        this.errors = [];
        if (this.titulo === "")
          this.errors.push("O título do trabalho não foi informado!");
        if (this.descricao_curta === "")
          this.errors.push("A descrição do trabalho não foi informada!");
        if (this.nome_companhia === "")
          this.errors.push("O nome da companhia não foi informado!");
        if (this.tamanho_companhia === "")
          this.errors.push("O tamanho da companhia não foi informado!");
        if (this.errors) {
          e.preventDefault();
          return false;
        } else {
          return true;
        }
      },
    },
  };
  Vue.createApp(AddJobApp).mount("#add-job-app");
</script>
{% endblock %}

jobs/templates/jobs/apply_for_job.html
{% extends 'core/base.html' %} {% block content %}
<h1 class="title">Apply For Job - {{ job.titulo }}</h1>
<form action="." method="post">
  {% csrf_token %} {% if form.errors %} {% for error in form.errors %}
  <div class="notification is-danger">{{ error }}</div>
  {% endfor %} {% endif %}
  <div class="field">
    <label for="id_conteudo">Conteúdo</label>
    <div class="control">
      <textarea class="textarea" name="conteudo" id="id_conteudo"></textarea>
    </div>
  </div>
  <div class="field">
    <label for="id_experiencia">Experiência</label>
    <div class="control">
      <textarea
        class="textarea"
        name="experiencia"
        id="id_experiencia"
      ></textarea>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <button class="button is-success">Enviar Aplicação</button>
    </div>
  </div>
</form>
{% endblock %}

jobs/templates/jobs/edit_job.html
{% extends 'core/base.html' %} {% block content %}
<div id="edit-job-app">
  <h1 class="title">Editar Trabalho</h1>
  <form action="." method="post" v-on:submit="validateForm()">
    {% csrf_token %} {% if form.errors %} {% for error in form.errors %}
    <div class="notification is-danger"><p>{{ error }}</p></div>
    {% endfor %} {% endif %}
    <div class="notification is-danger" v-if="errors.length">
      <p v-for="error in errors">[[ error ]]</p>
    </div>
    <fieldset class="box">
      <legend class="subtitle is-6">Informações Básicas</legend>
      <div class="field">
        <label class="label" for="id_titulo">Título</label>
        <div class="control">
          <input
            class="input"
            type="text"
            name="titulo"
            id="id_titulo"
            v-model="titulo"
            value="{% if job.titulo %}{{ job.titulo }}{% endif %}"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_descricao_curta">Descrição Curta</label>
        <div class="control">
          <textarea
            class="textarea"
            name="descricao_curta"
            id="id_descricao_curta"
            v-model="descricao_curta"
            value="{% if job.descricao_curta %}{{ job.descricao_curta }}{% endif %}"
          ></textarea>
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_descricao_longa">Descrição Longa</label>
        <div class="control">
          <textarea
            class="textarea"
            name="descricao_longa"
            id="id_descricao_longa"
          >
          {% if job.descricao_longa %}{{ job.descricao_longa }}{% endif %}
          </textarea>
        </div>
      </div>
    </fieldset>
    <fieldset class="box">
      <legend class="subtitle is-6">Informações da Companhia</legend>
      <div class="field">
        <label class="label" for="id_nome_companhia">Nome da Companhia</label>
        <div class="control">
          <input
            type="text"
            name="nome_companhia"
            id="id_nome_companhia"
            class="input"
            v-model="nome_companhia"
            value="{% if job.nome_companhia %}{{ job.nome_companhia }}{% endif %}"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_endereco_companhia"
          >Endereço da Companhia</label
        >
        <div class="control">
          <input
            type="text"
            name="endereco_companhia"
            id="id_endereco_companhia"
            class="input"
            value="{% if job.endereco_companhia %}{{ job.endereco_companhia }}{% endif %}"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_cep_companhia">CEP da Companhia</label>
        <div class="control">
          <input
            type="text"
            name="cep_companhia"
            id="id_cep_companhia"
            class="input"
            value="{% if job.cep_companhia %}{{ job.cep_companhia }}{% endif %}"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_cidade_companhia"
          >Cidade da Companhia</label
        >
        <div class="control">
          <input
            type="text"
            name="cidade_companhia"
            id="id_cidade_companhia"
            class="input"
            value="{% if job.cidade_companhia %}{{ job.cidade_companhia }}{% endif %}"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_pais_companhia">País da Companhia</label>
        <div class="control">
          <input
            type="text"
            name="pais_companhia"
            id="id_pais_companhia"
            class="input"
            value="{% if job.pais_companhia %}{{ job.pais_companhia }}{% endif %}"
          />
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_tamanho_companhia"
          >Tamanho da Companhia</label
        >
        <div class="control">
          <div class="select">
            <select
              name="tamanho_companhia"
              id="id_tamanho_companhia"
              v-model="tamanho_companhia"
            >
              <option value="tamanho_1-9" selected>1-9</option>
              <option value="tamanho_10-49">10-49</option>
              <option value="tamanho_50-99">50-99</option>
              <option value="tamanho_100">100+</option>
            </select>
          </div>
        </div>
      </div>
    </fieldset>
    <div class="field">
      <label class="label" for="id_status">Status do Trabalho</label>
      <div class="control">
        <div class="select">
          <select name="status" id="id_status">
            <option value="ativo" {% if job.status == 'ativo' %}selected{% endif %}>Ativo</option>
            <option value="ocupado" {% if job.status == 'ocupado' %}selected{% endif %}>Ocupado</option>
            <option value="arquivado" {% if job.status == 'arquivado' %}selected{% endif %}>Arquivado</option>
          </select>
        </div>
      </div>
    </div>
    <div class="field">
      <div class="control">
        <button class="button is-success">Salvar Modificações</button>
      </div>
    </div>
  </form>
</div>
{% endblock %} {% block scripts %}
<script>
  const EditJobApp = {
    data() {
      return {
        titulo: "{{ job.titulo }}",
        nome_companhia: "{{ job.nome_companhia }}",
        descricao_curta: "{{ job.descricao_curta }}",
        tamanho_companhia: "{{ job.tamanho_companhia }}",
        errors: [],
      };
    },
    delimiters: ["[[", "]]"],
    methods: {
      validateForm(e) {
        this.errors = [];
        if (this.titulo === "")
          this.errors.push("O título do trabalho não foi informado!");
        if (this.descricao_curta === "")
          this.errors.push("A descrição do trabalho não foi informada!");
        if (this.nome_companhia === "")
          this.errors.push("O nome da companhia não foi informado!");
        if (this.tamanho_companhia === "")
          this.errors.push("O tamanho da companhia não foi informado!");
        if (this.errors) {
          e.preventDefault();
          return false;
        } else {
          return true;
        }
      },
    },
  };
  Vue.createApp(EditJobApp).mount("#edit-job-app");
</script>
{% endblock %}

jobs/templates/jobs/job_detail.html
{% extends 'core/base.html' %} {% block content %}
<h1 class="title">{{ job.titulo }} - ({{ job.get_status_display }})</h1>
<p class="is-size-4">{{ job.descricao_curta }}</p>
<p>{{ job.descricao_longa }}</p>
<div class="box">
  <p><b>Nome da companhia: </b>{{ job.nome_companhia }}</p>
  {% if job.endereco_companhia %}
  <p><b>Endereço da Companhia: </b>{{ job.endereco_companhia }}</p>
  {% endif %} {% if job.cep_companhia %}
  <p><b>CEP da Companhia: </b>{{ job.cep_companhia }}</p>
  {% endif %} {% if job.cidade_companhia %}
  <p><b>Cidade da Companhia: </b>{{ job.cidade_companhia }}</p>
  {% endif %} {% if job.pais_companhia %}
  <p><b>País da Companhia: </b>{{ job.pais_companhia }}</p>
  {% endif %}
  <p><b>Tamanho da Companhia: </b>{{ job.get_tamanho_companhia_display }}</p>
</div>
<hr />
{% if job.status == 'ativo' %}
<a href="{% url 'apply_for_job' job.id %}" class="button is-success"
  >Aplicar para trabalho</a
>
{% else %}
<p>Este trabalho não está mais disponível</p>
{% endif %} {% endblock %}

jobs/templates/jobs/search.html
{% extends 'core/base.html' %} {% block content %}
<div id="search-app">
  <h1 class="title">Busca</h1>
  <form v-on:submit.prevent="performSearch()">
    <div class="columns">
      <div class="column is-4">
        <div class="field">
          <label for="id_query" class="label">Termo de busca</label>
          <div class="control">
            <input
              type="text"
              name="query"
              id="id_query"
              class="input"
              v-model="query"
            />
          </div>
        </div>
        <div class="field">
          <label for="id_tamanho_companhia" class="label"
            >Tamanho da Companhia</label
          >
          <div class="control">
            <div class="select">
              <select
                name="tamanho_companhia"
                id="id_tamanho_companhia"
                v-model="tamanho_companhia"
              >
                <option value="" selected>Todos os tamanhos</option>
                <option value="tamanho_1-9">1-9</option>
                <option value="tamanho_10-49">10-49</option>
                <option value="tamanho_50-99">50-99</option>
                <option value="tamanho_100">100+</option>
              </select>
            </div>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <button class="button is-success">Buscar</button>
          </div>
        </div>
      </div>
    </div>
  </form>
  <div v-if="jobs.length">
    <hr />
    <div class="notification mt-2" v-for="job in jobs" v-bind:key="job.id">
      <h3 class="is-size-4">[[ job.titulo ]]</h3>
      <p>[[ job.nome_companhia ]]</p>
      <a v-bind:href="job.url">Ver detalhes</a>
    </div>
  </div>
</div>
{% endblock %} {% block scripts %}
<script>
  const SearchApp = {
    data() {
      return {
        query: "",
        tamanho_companhia: "",
        jobs: [],
      };
    },
    delimiters: ["[[", "]]"],
    methods: {
      performSearch() {
        let data = {
          query: this.query,
          tamanho_companhia: this.tamanho_companhia,
        };

        fetch("/jobs/api/busca/", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": "{{ csrf_token }}",
          },
          body: JSON.stringify(data),
        })
          .then((response) => {
            return response.json();
          })
          .then((result) => {
            this.jobs = result.jobs;
          })
          .catch((error) => console.log("Erro!", error));
      },
    },
  };
  Vue.createApp(SearchApp).mount("#search-app");
</script>
{% endblock %}